spring:
  application:
    name: charset.school

  main:
    allow-bean-definition-overriding: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  session:
    jdbc:
      cleanup-cron: "-"

app:
  remember-me:
    key: test-only-remember-me-key
